name: custom workflow
on: push
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: make setup
        run: npm install
      - name:  make test
        run: npm test
      - name: make lint
        run: npx eslint .


